.gitignore
package-lock.json
package.json
src/components/twilio-voice-basic-call-control/handler.js
src/components/twilio-voice-basic-call-control/public/index.html
src/components/twilio-voice-basic-call-control/public/index.js
src/components/twilio-voice-basic-call-control/public/twilio-voice-basic-call-control.js
src/components/twilio-voice-dialer/public/index.html
src/components/twilio-voice-dialer/public/index.js
src/components/twilio-voice-dialer/public/twilio-voice-dialer.js
src/config.js
src/server.js

Directory structure and dynamic loading of components.

VBLOCKS-3402 Directory structure and dynamic loading of components

---

README.md
example.env
package-lock.json
package.json
src/components/twilio-voice-basic-call-control/handler.js
src/components/twilio-voice-basic-call-control/routes.js
src/components/twilio-voice-dialer/public/index.js
src/components/twilio-voice-dialer/public/twilio-voice-dialer.js
src/components/twilio-voice-dialer/routes.js
src/config.js
src/server.js

VBLOCKS 3403 - Dialer endpoints.
Please note that there's no authentication mechanism implemented. However, we will add notes later where a customer would do validation and such. See VBLOCKS-3486

VBLOCKS 3403 - Dialer endpoints

---

example.env
src/components/twilio-voice-dialer/public/twilio-voice-dialer.js

https://twilio-engineering.atlassian.net/browse/VBLOCKS-3461
Outgoingcall

[VBLOCKS-3461] feat: outgoing call

---

example.env
src/components/twilio-voice-basic-call-control/routes.js
src/components/twilio-voice-dialer/public/index.js
src/components/twilio-voice-dialer/routes.js
src/config.js

Vblocks 3455 Hold endpoint for any client leg

Vblocks 3455 Hold endpoint for any client leg

---

src/components/twilio-voice-dialer/public/index.html
src/components/twilio-voice-dialer/public/twilio-voice-dialer.js

https://twilio-engineering.atlassian.net/browse/VBLOCKS-3462
Register status
Incoming call

[VBLOCKS-3462] Feat: incoming call

---

src/components/twilio-voice-dialer/public/index.js
src/components/twilio-voice-dialer/public/twilio-voice-dialer.js

[IDL](https://docs.google.com/document/d/1rHlTs9y7TcNZLaHx2aHJAgo7tEwqyvn-Izbf0vkoLYQ/edit)
[VBLOCKS-3463](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3463)
- onTokenWillExpire (EventHandler)
- onIncoming (EventHandler)

feat: onIncoming and onTokenWillExpire

---

src/components/twilio-voice-basic-call-control/public/twilio-voice-basic-call-control.js
src/components/twilio-voice-basic-call-control/routes.js

[VBLOCKS-3632](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3632)
- Implement Mute functionality in the `<twilio-voice-basic-call-control>` component.

[VBLOCKS-3632] Feat: mute implementation

---

example.env
src/components/twilio-voice-basic-call-control/routes.js
src/components/twilio-voice-dialer/routes.js
src/config.js

[VBLOCKS-3486](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3486)
- webhook validation for express
- reference links

[VBLOCKS-3486] basic security and notes

---

src/components/twilio-voice-basic-call-control/public/twilio-voice-basic-call-control.js
src/components/twilio-voice-basic-call-control/routes.js

- Remove Participant from conference

[VBLOCKS-3799] Feat: remove participant

---

src/common/routes.js
src/components/twilio-voice-basic-call-control/public/twilio-voice-basic-call-control.js

Steps
- agent1 calls customer
- agent1 forwards call to agent2
- agent1 immediately drops from call after "forward" button is clicked
- agent2 picks up call and continues conversation with customer

[VBLOCKS-3800] feat: cold transfer

---

README.md
example.env

VBLOCKS-3815 Update README.md

---

.gitignore
src/common/routes.js
src/components/twilio-voice-basic-call-control/routes.js
src/components/twilio-voice-dialer/routes.js
src/components/twilio-voice-monitoring/public/index.html
src/components/twilio-voice-monitoring/public/index.js
src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js
src/components/twilio-voice-monitoring/routes.js

Monitor conference `StatusCallbackEvents`
https://www.twilio.com/docs/voice/twiml/conference#attributes-statuscallbackevent  
UI - Text display box to track statuscallbackevents

[VBLOCKS-3954] feat: status

---

src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js

https://twilio-engineering.atlassian.net/browse/VBLOCKS-3958
Logged warnings:

[VBLOCKS-3958] feat: log call warnings

---

src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js

Error logging for Monitoring Component

[VBLOCKS-3959] feat: error logging

---

src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js

[VBLOCKS-3957](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3957)
Handle quality warnings

[VBLOCKS-3957] feat: handle quality warnings

---

README.md
package.json

[VBLOCKS-4113] chore: clarify handling of env vars

---

src/common/routes.js
src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js
src/components/twilio-voice-monitoring/routes.js

[VBLOCKS-4076](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4076)
- Allow `caller` to see progress/status of call leg for `callee`
- use UDM to send progress/status to `caller`

[VBLOCKS-4047] feat: call leg status

---

src/components/twilio-voice-dialer/public/twilio-voice-dialer.js
src/components/twilio-voice-monitoring/public/twilio-voice-monitoring.js
src/components/twilio-voice-monitoring/routes.js

[VBLOCKS-4077](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4077)
- call logging
- device logging

[VBLOCKS-4077] feat: device logging

---

README.md
example.env

Polish up README
https://twilio-engineering.atlassian.net/browse/VBLOCKS-5006

[VBLOCKS-5006] Refactor: readme

---

README.md
example.env

Sync `readme` & `.env` with docs update: https://github.com/twilio-internal/docs/pull/4562/files

[VBLOCKS-5119] chore: sync readme with docs
